### boiler plate config
out_dir: /data1/shahs3/users/preskaa/AMLproteogenomics/data/APS028_AML_PG2_analysis/fragpipe23_out
workflow_dir: /data1/shahs3/users/preskaa/AMLproteogenomics/data/APS028_AML_PG2_analysis/fragpipe23_workflows
samplesheet: config/PG2_Frankfurt_AML_proteomics_clean.tsv
# directories containing predicted proteomes from from PG2 permissive and restrictive runs
PG2_dirs: ["/data1/kentsisa/AML_proteogenomics/PG2_restrictive/Proj_B-101-986",
          "/data1/kentsisa/AML_proteogenomics/PG2_permissive/Proj_B-101-985"]
# choose which proteomegenerator search databases to search
pg_dbs: ["PG2_restrictive", "PG2_permissive", "swissprot"]
# path to fragpipe config tools which can't be dockerized
fragpipe_config_tools: /home/preskaa/250624_fragpipe_config_tools
# run against swissprot as well? provide a fasta file here where
# decoys and contaminants have already been added (can download and add decoys/contams with Fragpipe GUI)
# also provide samplesheet with normal controls (CD34+ cells)
swissprot:
  activate: True
  fasta: /data1/shahs3/reference/ref-sarcoma/swissprot/2024-09-06-decoys-reviewed-isoforms-contam-UP000005640.fas
  normal_samplesheet: config/Frankfurt_normal_samples.tsv