### boiler plate config
out_dir: /data1/shahs3/users/preskaa/AMLproteogenomics/data/APS032_PG3_Frankfurt/test
workflow_dir: /data1/shahs3/users/preskaa/AMLproteogenomics/data/APS032_PG3_Frankfurt/fragpipe23_workflows
samplesheet: config/PG2_Frankfurt_AML_proteomics_clean_test.tsv
# directories containing predicted proteomes from from PG2 permissive and restrictive runs
PG2_dirs: ["/data1/kentsisa/AML_proteogenomics/PG2_restrictive/Proj_B-101-986"]
# choose which proteomegenerator search databases to search
pg_dbs: ["PG3_proteome"]
# reannotate PG2 headers to UniProt style (need transcriptome gtfs to be available)
# provide swissprot fasta without decoys and contams here for reannotation
reannotate:
  activate: False
  haplotypes: [1, 2]
  ref_gtf: /data1/shahs3/reference/ref-sarcoma/GRCh38/v45/gencode.v45.primary_assembly.annotation.gtf
  swissprot: /data1/shahs3/reference/ref-sarcoma/blast_databases/swissprot_human_250206/2025-02-06-reviewed-isoforms-UP000005640.fas
# run fragpipe against reannotated proteomes
fragpipe:
  activate: False
# path to fragpipe config tools which can't be dockerized
fragpipe_config_tools: /home/preskaa/250624_fragpipe_config_tools
# run against swissprot as well? provide a fasta file here where
# decoys and contaminants have already been added (can download and add decoys/contams with Fragpipe GUI)
# also provide samplesheet with normal controls (CD34+ cells)
swissprot:
  activate: False
  fasta: /data1/shahs3/reference/ref-sarcoma/swissprot/2024-09-06-decoys-reviewed-isoforms-contam-UP000005640.fas
# run against a unified proteome for all samples
# decoys and contaminants have NOT been added
# also provide samplesheet with normal controls (CD34+ cells)
unified_proteome:
  activate: True
  fasta: /data1/shahs3/isabl_data_lake/analyses/97/45/49745/results/proteome/NDR_DEFAULT/merge.proteome.fasta
## provide spreadsheet of normal samples (CD34+ cells) for swissprot and unified proteome searches
normal_samplesheet: null
